# Generated by Django 4.2.28 on 2026-03-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_usernotification'),
        ('accounts', '0021_merge_20260316_0049'),
    ]

    operations = [
    ]
