# Generated by Django 4.2.28 on 2026-03-18 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_merge_0015_usernotification_0021_merge_20260316_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperuserImpersonationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_impersonate_any', models.BooleanField(default=False)),
                ('allowed_departments', models.CharField(blank=True, default='', help_text='Comma-separated department codes, or empty for all', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for no expiry', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_target_roles', models.ManyToManyField(blank=True, help_text='Leave empty to allow all roles', to='accounts.role')),
                ('superuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Superuser Impersonation Permission',
                'verbose_name_plural': 'Superuser Impersonation Permissions',
                'unique_together': {('superuser',)},
            },
        ),
        migrations.CreateModel(
            name='SuperuserImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed - Invalid User'), ('DENIED', 'Denied - Insufficient Permissions'), ('DISABLED', 'Denied - Target User Inactive')], default='SUCCESS', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accessed_until', models.DateTimeField(blank=True, help_text='When this impersonation session should expire', null=True)),
                ('superuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impersonations_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['superuser', '-created_at'], name='accounts_su_superus_57415e_idx'), models.Index(fields=['target_user', '-created_at'], name='accounts_su_target__6af2ae_idx'), models.Index(fields=['status', '-created_at'], name='accounts_su_status_83b8a9_idx')],
            },
        ),
    ]
