# Generated by Django 4.2.28 on 2026-03-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_announcement_permissions'),
        ('accounts', '0027_add_hr_view_any_application_permission'),
    ]

    operations = [
    ]
