# Generated by Django 4.2.28 on 2026-03-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0070_alter_studentcourseenrollment_course_and_more'),
        ('OBE', '0053_marks_scope_by_teaching_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review2PublishedSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review2_published_sheet', to='academics.subject')),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review2_published_sheets', to='academics.teachingassignment')),
            ],
        ),
        migrations.CreateModel(
            name='Review1PublishedSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review1_published_sheet', to='academics.subject')),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review1_published_sheets', to='academics.teachingassignment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='review2publishedsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', False)), fields=('subject', 'teaching_assignment'), name='unique_review2_published_sheet_subject_ta'),
        ),
        migrations.AddConstraint(
            model_name='review2publishedsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', True)), fields=('subject',), name='unique_review2_published_sheet_subject_legacy'),
        ),
        migrations.AddConstraint(
            model_name='review1publishedsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', False)), fields=('subject', 'teaching_assignment'), name='unique_review1_published_sheet_subject_ta'),
        ),
        migrations.AddConstraint(
            model_name='review1publishedsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('teaching_assignment__isnull', True)), fields=('subject',), name='unique_review1_published_sheet_subject_legacy'),
        ),
    ]
