# Generated by Copilot on 2026-03-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('OBE', '0055_remove_review2publishedsheet_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObeBatchQpPatternOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=50)),
                ('question_paper_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exam', models.CharField(max_length=50)),
                ('pattern', models.JSONField(default=dict)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_qp_overrides', to='academics.batch')),
            ],
            options={
                'db_table': 'obe_batch_qp_pattern_override',
            },
        ),
        migrations.AddIndex(
            model_name='obebatchqppatternoverride',
            index=models.Index(fields=['batch', 'exam'], name='obe_batch_q_batch_i_9e8b71_idx'),
        ),
        migrations.AddIndex(
            model_name='obebatchqppatternoverride',
            index=models.Index(fields=['class_type', 'question_paper_type', 'exam'], name='obe_batch_q_class_t_b7f3a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='obebatchqppatternoverride',
            constraint=models.UniqueConstraint(fields=('batch', 'class_type', 'question_paper_type', 'exam'), name='unique_batch_qp_pattern_override_key'),
        ),
    ]
