# Generated by Django 4.2.28 on 2026-03-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0057_merge_20260328_1125'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obebatchqppatternoverride',
            new_name='obe_batch_q_batch_i_d7999f_idx',
            old_name='obe_batch_q_batch_i_9e8b71_idx',
        ),
        migrations.RenameIndex(
            model_name='obebatchqppatternoverride',
            new_name='obe_batch_q_class_t_226be8_idx',
            old_name='obe_batch_q_class_t_b7f3a5_idx',
        ),
    ]
