# Generated by Django 4.2.28 on 2026-04-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBE', '0059_finalinternalmark'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='finalinternalmark',
            new_name='obe_final_i_subject_b203e4_idx',
            old_name='obe_final_i_subject_8c1d53_idx',
        ),
        migrations.RenameIndex(
            model_name='finalinternalmark',
            new_name='obe_final_i_teachin_61dbde_idx',
            old_name='obe_final_i_teachin_b6f785_idx',
        ),
        migrations.RenameIndex(
            model_name='finalinternalmark',
            new_name='obe_final_i_compute_16dd43_idx',
            old_name='obe_final_i_compute_a8e65f_idx',
        ),
    ]
