# Generated by Django 4.2.28 on 2026-03-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COE', '0004_coearrearstudent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coearrearstudent',
            new_name='COE_coearre_departm_1a75b7_idx',
            old_name='COE_coearre_departm_86f297_idx',
        ),
        migrations.RenameIndex(
            model_name='coearrearstudent',
            new_name='COE_coearre_course__dec265_idx',
            old_name='COE_coearre_course__6840a4_idx',
        ),
    ]
