# Generated by Django 4.2.28 on 2026-04-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_attendance", "0016_merge_20260401_1325"),
        ("staff_attendance", "0016_merge_20260402_0958"),
    ]

    operations = [
    ]
