# Generated by Django 4.2.28 on 2026-03-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_api', '0005_brandingeventlog'),
        ('template_api', '0005_encrypt_service_tokens'),
    ]

    operations = [
    ]
