# Generated by Django 5.2.11 on 2026-03-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0056_add_subject_batch_to_attendance_session"),
        ("academics", "0058_batch_course_nullable_dept_direct"),
    ]

    operations = []
