# Generated by Django 4.2.28 on 2026-03-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0052_rfreader_models'),
        ('academics', '0059_add_rfid_uid_to_studentprofile'),
    ]

    operations = [
    ]
