# Generated by Django 5.2.5 on 2026-03-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0059_merge_20260309_0937'),
        ('academics', '0060_merge_20260309_0757'),
    ]

    operations = [
    ]
