# Generated by Django 4.2.28 on 2026-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0061_merge_20260310_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='rfid_uid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='RFID card UID (e.g. 539EA5BB) assigned by the physical scanner.', max_length=32),
        ),
    ]
