# Generated by Django 4.2.28 on 2026-03-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0062_studentcourseenrollment'),
        ('academics', '0068_merge_20260313_1122'),
    ]

    operations = [
    ]
