# Generated by Django 4.2.28 on 2026-03-30 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0073_department_is_teaching'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_uid', models.CharField(db_index=True, editable=False, help_text='Auto-generated 16-character alphanumeric unique ID.', max_length=16, unique=True)),
                ('designation', models.CharField(blank=True, default='', max_length=128)),
                ('organisation', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user account this external staff profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ext_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Staff Profile',
                'verbose_name_plural': 'External Staff Profiles',
                'ordering': ('-created_at',),
            },
        ),
    ]
