# Generated by Django 5.2.11 on 2026-03-10 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0059_merge_20260309_0937"),
        ("timetable", "0005_specialtimetable_specialtimetableentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("from_subject_text", models.CharField(blank=True, max_length=256)),
                ("to_date", models.DateField()),
                ("to_subject_text", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for the swap request"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the approver/rejecter",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was approved/rejected",
                        null=True,
                    ),
                ),
                (
                    "from_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_from_requests",
                        to="timetable.timetableslot",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_swap_requests",
                        to="academics.staffprofile",
                    ),
                ),
                (
                    "requested_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_swap_requests",
                        to="academics.staffprofile",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_swap_requests",
                        to="academics.section",
                    ),
                ),
                (
                    "to_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_to_requests",
                        to="timetable.timetableslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Period Swap Request",
                "verbose_name_plural": "Period Swap Requests",
                "ordering": ("-created_at",),
            },
        ),
    ]
