# Generated by GitHub Copilot on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_add_formversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
