# Generated by Django 4.2.28 on 2026-03-08 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0008_approvalflow_allow_multiple_per_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gatepass_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gatepass_scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepass_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='sla_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Total SLA for this flow in hours (measured from submission).', null=True),
        ),
    ]
