# Generated by Django 4.2.28 on 2026-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_add_tag_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All Users'), ('DEPARTMENT', 'Department'), ('CLASS', 'Class'), ('ROLE', 'Role')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-created_at'], name='announcemen_created_da46df_idx'),
        ),
    ]
