directories:
  output: release
  buildResources: build
appId: in.krgi.idcs.gate
productName: IDCS GATE
files:
  - filter:
      - dist/**
win:
  icon: build/icon.ico
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  installerHeaderIcon: build/icon.ico
electronVersion: 32.3.3
