# Generated by Django 4.2.28 on 2026-03-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_salary', '0004_bank_declaration_and_staff_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarymonthlyinput',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarymonthpublish',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
