path = r'g:\IDCS-NEW\IDCS-Restart\backend\idcsscan\views.py'
lines = open(path, encoding='utf-8').readlines()

new_block = (
    "        # \u2500\u2500 4. Application found but preceding steps still blocking \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "        if blocking_app is not None:\n"
    "            timeline = _build_timeline(blocking_app, blocking_flow)\n"
    "            steps = list(blocking_flow.steps.select_related('role').order_by('order'))\n"
    "            actions = {a.step_id: a.action for a in blocking_app.actions.all()}\n"
    "            blocking_step = None\n"
    "            for step in steps:\n"
    "                if step.is_final and step.role and step.role.name.upper() == 'SECURITY':\n"
    "                    break\n"
    "                act = actions.get(step.id)\n"
    "                if step.is_starter:\n"
    "                    if not act:\n"
    "                        blocking_step = step\n"
    "                        break\n"
    "                else:\n"
    "                    if not act or act not in ('APPROVED', 'SKIPPED'):\n"
    "                        blocking_step = step\n"
    "                        break\n"
    "            msg = f'Application #{blocking_app.id} is not fully approved yet'\n"
    "            if blocking_step:\n"
    "                msg += f' \u2014 step {blocking_step.order} ({blocking_step.role.name}) is pending'\n"
    "            return Response({\n"
    "                'allowed': False,\n"
    "                'reason': 'not_fully_approved',\n"
    "                'message': msg + '.',\n"
    "                'student': student_data,\n"
    "                'application_id': blocking_app.id,\n"
    "                'approval_timeline': timeline,\n"
    "            }, status=status.HTTP_200_OK)\n"
    "\n"
    "        # \u2500\u2500 5. Already gate-scanned \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "        already_scanned = app_models.Application.objects.filter(\n"
    "            student_profile=sp,\n"
    "            gatepass_scanned_at__isnull=False,\n"
    "        ).order_by('-gatepass_scanned_at').first()\n"
    "\n"
    "        if already_scanned:\n"
    "            flow = _get_flow_for_application(already_scanned)\n"
    "            timeline = _build_timeline(already_scanned, flow) if flow else []\n"
    "            return Response({\n"
    "                'allowed': False,\n"
    "                'reason': 'already_scanned',\n"
    r"                'message': f'Student already exited at {already_scanned.gatepass_scanned_at.strftime(\"%I:%M %p\")}.',"
    "\n"
    "                'student': student_data,\n"
    "                'approval_timeline': timeline,\n"
    "            }, status=status.HTTP_200_OK)\n"
    "\n"
)

result = lines[:372] + [new_block] + lines[414:]
open(path, 'w', encoding='utf-8').writelines(result)
count = sum(1 for _ in open(path, encoding='utf-8'))
print('Done. Total lines:', count)
